version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket bbcweather --output-template-file outputSamTemplate.yaml
      - pip install -r requirements.txt
  build:
    commands:
      - python -m pytest --junitxml=test_reports/report.xml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
reports:
  pytest_reports:
    files:
      - report.xml
    base-directory: test_reports
    file-format: JUNITXML