version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket bbcweather --output-template-file outputSamTemplate.yaml
      - pip install -r requirements.txt -t .
  build:
    commands:
      - python -m pytest --junitxml=report/pytest.xml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
reports:
  pytest_reports:
    files:
      - pytest.xml
    base-directory: report
    file-format: JUNITXML