AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'BBC Weather logger'
Resources:
  BBCWeatherLogger:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      Description: 'Scraper that accesses BBC Weather and logs hourly data'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::837506829712:role/bbcweather_lambda_role'
      Events:
        weather:
          Type: Api
          Properties:
            Path: /weather
            Method: get